language: python
python: 3.5
sudo: required
dist: xenial

services:
  - docker

env:
- WHEELHOUSE=$HOME/.cache/wheelhouse PIP_FIND_LINKS=file://$WHEELHOUSE PIP_WHEEL_DIR=$WHEELHOUSE

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/wheelhouse"
  - portiaui/node_modules
  - portiaui/bower_components

install:
- cd portiaui
- nvm install 6.10.0
- nvm use 6.10.0
- npm install -g bower
- npm install
- bower install
- cd ..

before_script:
  - docker build -t scrapinghub/portia .
  - docker run scrapinghub/portia /app/docker/test-container.sh

script:
- cd ./portiaui
- npm rebuild node-sass
- npm test

before_deploy:
- cd ../slybot
- pip install twine
- sudo chown -R $USER .

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: S5hZT2YBncUSkPTyR5RUQnACfTsW2ZtpHeQucIamKWN+xkE8KK9O0cWUMuKQ0q3U5ShFkZdhO4PnBjvtP54Dq9IogJAudkDJCylctf4qGoIlWu01mAoJzcUfrS5KW+VolF/opBJObwG38EIOOsVy9UYq7DeQcryAAG1RuMjONAk=
  on:
    all_branches: true
    tags: true
    repo: scrapinghub/portia
    condition: "$TRAVIS_TAG =~ ^slybot-[0-9][.][0-9]*"
